application:
  name: cheque-mate
  project: Cheque-Mate
  cloud_region: aws/ca-central-1
databases:
- type: postgresql
  version: 12
  name: cheque-mate
routers:
- name: main
  routes:
  - application_name: cheque-mate
    paths:
    - /
  custom_domains:
  - branch: master
    domain: chequemate.work
