application:
  name: cheque-mate
  project: Cheque Mate
  cloud_region: aws/us-east-2
databases:
- type: postgresql
  version: "12"
  name: my-postgresql-8261476
routers:
- name: main
  routes:
  - application_name: cheque-mate
    paths:
    - /
