version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./data:/var/lib/postgresql/data
  server:
    build: ./server/
    volumes:
      - ./server:/srv/server
    ports:
      - 9000:9000
    depends_on:
      - db
    links:
      - db
    command: npm run dev
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/client
    ports:
      - 3000:3000
    links:
      - server
    command: npm run start
